// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {main} from '../models';
import {config} from '../models';

export function AddBackupDirectory(arg1:string):Promise<void>;

export function ClearLocalCatalog():Promise<void>;

export function DeleteAllServerBackups():Promise<void>;

export function DeleteServerBackup(arg1:number):Promise<void>;

export function GetBackupDates():Promise<Array<string>>;

export function GetBackupHistory(arg1:number):Promise<Array<backup.BackupEntry>>;

export function GetBackupStatus():Promise<backup.BackupStatus>;

export function GetCatalogDirectories():Promise<Array<string>>;

export function GetCatalogFiles():Promise<Array<main.CatalogFileInfo>>;

export function GetCatalogFilesAtDate(arg1:string):Promise<Array<main.CatalogFileInfo>>;

export function GetConfig():Promise<config.Config>;

export function GetDataDir():Promise<string>;

export function GetDevices():Promise<Array<backup.Device>>;

export function GetFileHistory(arg1:string):Promise<Array<main.FileVersionInfo>>;

export function GetFilesInDirectory(arg1:string):Promise<Array<main.CatalogFileInfo>>;

export function GetQuota():Promise<backup.QuotaInfo>;

export function GetServerBackups():Promise<Array<backup.BackupEntry>>;

export function GetUsage():Promise<backup.UsageInfo>;

export function HasLocalCatalog():Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function RecoverCatalog():Promise<void>;

export function RegisterDevice(arg1:string):Promise<backup.Device>;

export function RemoveBackupDirectory(arg1:string):Promise<void>;

export function RestoreDirectory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestoreFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestoreToDate(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetEncryptionKey(arg1:string):Promise<void>;

export function StartBackup():Promise<void>;

export function StartRestore(arg1:number,arg2:string):Promise<void>;

export function StopBackup():Promise<void>;
