// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBackupDirectory(arg1) {
  return window['go']['main']['App']['AddBackupDirectory'](arg1);
}

export function ClearLocalCatalog() {
  return window['go']['main']['App']['ClearLocalCatalog']();
}

export function DeleteAllServerBackups() {
  return window['go']['main']['App']['DeleteAllServerBackups']();
}

export function DeleteServerBackup(arg1) {
  return window['go']['main']['App']['DeleteServerBackup'](arg1);
}

export function GetBackupDates() {
  return window['go']['main']['App']['GetBackupDates']();
}

export function GetBackupHistory(arg1) {
  return window['go']['main']['App']['GetBackupHistory'](arg1);
}

export function GetBackupStatus() {
  return window['go']['main']['App']['GetBackupStatus']();
}

export function GetCatalogDirectories() {
  return window['go']['main']['App']['GetCatalogDirectories']();
}

export function GetCatalogFiles() {
  return window['go']['main']['App']['GetCatalogFiles']();
}

export function GetCatalogFilesAtDate(arg1) {
  return window['go']['main']['App']['GetCatalogFilesAtDate'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetFileHistory(arg1) {
  return window['go']['main']['App']['GetFileHistory'](arg1);
}

export function GetFilesInDirectory(arg1) {
  return window['go']['main']['App']['GetFilesInDirectory'](arg1);
}

export function GetQuota() {
  return window['go']['main']['App']['GetQuota']();
}

export function GetServerBackups() {
  return window['go']['main']['App']['GetServerBackups']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetUsage() {
  return window['go']['main']['App']['GetUsage']();
}

export function HasLocalCatalog() {
  return window['go']['main']['App']['HasLocalCatalog']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RecoverCatalog() {
  return window['go']['main']['App']['RecoverCatalog']();
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function RegisterDevice(arg1) {
  return window['go']['main']['App']['RegisterDevice'](arg1);
}

export function RemoveBackupDirectory(arg1) {
  return window['go']['main']['App']['RemoveBackupDirectory'](arg1);
}

export function RestoreDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreDirectory'](arg1, arg2, arg3);
}

export function RestoreFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreFile'](arg1, arg2, arg3);
}

export function RestoreToDate(arg1, arg2) {
  return window['go']['main']['App']['RestoreToDate'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetEncryptionKey(arg1) {
  return window['go']['main']['App']['SetEncryptionKey'](arg1);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function StartBackup() {
  return window['go']['main']['App']['StartBackup']();
}

export function StartRestore(arg1, arg2) {
  return window['go']['main']['App']['StartRestore'](arg1, arg2);
}

export function StopBackup() {
  return window['go']['main']['App']['StopBackup']();
}
